events {}

http {
  upstream auth_service {
    server user-auth:3001;
  }

  upstream frontend_service {
    server frontend:3000;
  }

  server {
    listen 80;

    location /api/auth/ {
      rewrite ^/api/auth/(.*) /$1 break;
      proxy_pass http://auth_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
      proxy_pass http://frontend_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}