events {}

http {
  upstream user_service {
    server host.docker.internal:3001;
  }

  upstream auth_service {
    server host.docker.internal:5001; 
  }

  upstream frontend_service {
    server host.docker.internal:5173;
  }

  server {
    listen 80;

    location /api/auth/ {
      rewrite ^/api/auth/(.*) /$1 break;
      proxy_pass http://auth_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/users/ {
      rewrite ^/api/users/(.*) /$1 break;
      proxy_pass http://user_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      proxy_pass http://frontend_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}